### ISSUE TITLE
Eden Treaty: slow typescript intellisense

### ISSUE THREAD

**Issue by Fumaz** [elysiajs/eden#19]
Hi, I'm using Elysia with Eden Treaty and I use multiple Elysia instances, some of them having prefixes to keep the code tidy.
However, when trying to use Eden Treaty, the intellisense is really slow and most of the time it times out and just doesn't work at all.

**Comment by SaltyAom** [comment]
Please leave this issue open until we get Elysia to 0.7

**Comment by Fumaz** [comment]
Having the same issue with elysia 0.7.0 and @elysiajs/eden 0.7.0

**Comment by Fumaz** [comment]
It actually gives me the following TypeScript error:

<html>TS2344: Type 'Elysia&lt;&quot;&quot;, { request: { [x: string]: any; }; store: { [x: string]: any; }; }, { type: { [x: string]: any; }; error: { [x: string]: any; }; }, { body: unknown; headers: unknown; query: unknown; params: unknown; cookie: unknown; response: unknown; }, any, false&gt;' does not satisfy the constraint 'Elysia&lt;any, any, { type: {}; error: {}; }, {}, {}, false&gt;'.<br/>Types of property 'onError' are incompatible.<br/>Type '&lt;Schema extends RouteSchema = {}&gt;(handler: ErrorHandler&lt;{ [x: string]: any; }, MergeSchema&lt;Schema, { body: unknown; headers: unknown; query: unknown; params: unknown; cookie: unknown; response: unknown; }&gt;, { request: { [x: string]: any; }; store: { ...; }; }&gt;) =&gt; Elysia&lt;...&gt;' is not assignable to type '&lt;Schema extends RouteSchema = {}&gt;(handler: ErrorHandler&lt;{}, MergeSchema&lt;Schema, {}&gt;, any&gt;) =&gt; Elysia&lt;&quot;&quot;, { request: { [x: string]: any; }; store: { [x: string]: any; }; }, { ...; }, { ...; }, any, false&gt;'.<br/>Types of parameters 'handler' and 'handler' are incompatible.<br/>Types of parameters 'context' and 'context' are incompatible.<br/>Type '{ [x: string]: any; body: unknown; query: Record&lt;string, string | null&gt;; params: never; headers: Record&lt;string, string | null&gt;; cookie: Record&lt;string, Cookie&lt;any&gt;&gt;; ... 5 more ...; error: Readonly&lt;...&gt;; } | ... 5 more ... | { ...; }' is not assignable to type '{ [x: string]: any; request: Request; code: &quot;UNKNOWN&quot;; error: Readonly&lt;Error&gt;; set: { headers: Record&lt;string, string&gt; &amp; { 'Set-Cookie'?: string | string[] | undefined; }; status?: number | ... 60 more ... | undefined; redirect?: string | undefined; cookie?: Record&lt;...&gt; | undefined; }; } | ... 4 more ... | { ...; }'.<br/>Type '{ [x: string]: any; body: unknown; query: Record&lt;string, string | null&gt;; params: never; headers: Record&lt;string, string | null&gt;; cookie: Record&lt;string, Cookie&lt;any&gt;&gt;; ... 5 more ...; error: Readonly&lt;...&gt;; }' is not assignable to type '{ [x: string]: any; request: Request; code: &quot;UNKNOWN&quot;; error: Readonly&lt;Error&gt;; set: { headers: Record&lt;string, string&gt; &amp; { 'Set-Cookie'?: string | string[] | undefined; }; status?: number | ... 60 more ... | undefined; redirect?: string | undefined; cookie?: Record&lt;...&gt; | undefined; }; } | ... 4 more ... | { ...; }'.<br/>Type '{ [x: string]: any; body: unknown; query: Record&lt;string, string | null&gt;; params: never; headers: Record&lt;string, string | null&gt;; cookie: Record&lt;string, Cookie&lt;any&gt;&gt;; ... 5 more ...; error: Readonly&lt;...&gt;; }' is not assignable to type '{ [x: string]: any; request: Request; code: &quot;INVALID_COOKIE_SIGNATURE&quot;; error: Readonly&lt;InvalidCookieSignature&gt;; set: { headers: Record&lt;string, string&gt; &amp; { ...; }; status?: number | ... 60 more ... | undefined; redirect?: string | undefined; cookie?: Record&lt;...&gt; | undefined; }; }'.<br/>Types of property 'code' are incompatible.<br/>Type 'string' is not assignable to type '&quot;INVALID_COOKIE_SIGNATURE&quot;'.

**Comment by patlux** [comment]
same. I also have to import `@elysiajs/eden/fetch` instead of `@elysiajs/eden`, otherwise it returns just `any`.

![CleanShot 2023-09-20 at 17 22 42](https://github.com/elysiajs/eden/assets/4481570/3eb247cc-203c-4464-9274-0e35fbf7acfd)

**Comment by patlux** [comment]
It was fixed with the latest release :)

**Comment by MatthewAry** [comment]
Still seeing some weird TS errors that I can't really make sense of when using edenTreaty.
```
Type 'Elysia<"", { request: { readonly prisma: () => PrismaClient<{ log: ("query" | "error")[]; }, never, DefaultArgs>; readonly bearer: string | undefined; userContext: { ...; }; }; store: {}; }, { ...; }, { ...; }, { ...; }, false>' does not satisfy the constraint 'Elysia<any, any, any, any, any, any>'.
  Types have separate declarations of a private property 'dependencies'.
```
