### ISSUE TITLE
Treaty and Dependency Injection

### ISSUE THREAD

**Issue by artecoop** [elysiajs/eden#21]
Hi!
In order to use some feature of elysia like dependency injection (https://elysiajs.com/patterns/dependency-injection.html), I split the code into multiple file:

First, a state for the database
```ts
// setup.ts
export const setup = new Elysia({ name: 'setup' })
    .state('redis', redis)
```

```ts
// routes/auth.ts
import { Elysia } from 'elysia';

import { setup } from '../setup';

export const authRouter = new Elysia({prefix: "/auth"})
    .use(setup)
    .post('/login', async (context) => { ... })
    .post('/logout', async (context) => { ... }));
```

```ts
// routes/foo.ts
import { Elysia } from 'elysia';

import { setup } from '../setup';

export const fooRouter = new Elysia({prefix: "/foo"})
    .use(setup)
    .get('/', async (context) => { ... })
    .post('/manage', async (context) => { ... }));
```

and finally the main entry point for my app

```ts
// server.ts
import { Elysia } from 'elysia';

import { authRouter } from './routes/auth';
import { fooRouter } from './routes/foo';

const app = new Elysia()
    .use(authRouter)
    .use(fooRouter)
    .listen(6001);

export type App = typeof app;

console.log(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`);
```

Working as expected, manually querying various endpoints.

When using Treaty, I get an empty elysia app on the client side
<img width="510" alt="Screenshot 2023-09-20 at 10 09 36" src="https://github.com/elysiajs/eden/assets/52246878/94929823-5635-46fd-b096-37f959cf836b">

Any idea where my code fails?

Thanks in advance!

**Comment by G9000** [comment]
any workaround? was wondering why my eden type not working at all

**Comment by fredericoo** [comment]
Can’t replicate, seems to have been fixed in a newer releaase since the issue was posted?

![CleanShot 2024-01-08 at 22 21 32@2x](https://github.com/elysiajs/eden/assets/45042736/07086e55-7022-421d-9929-59183f409dc5)

**Comment by pandrRe** [comment]
This still does not work for me.

**Comment by rubfergor** [comment]
This is still happening to me too on "elysia": "~1.1.17" and "@elysiajs/eden": "~1.1.3", with the same structure as @artecoop, which basically means I either create an humoungous index or I can't use types
